version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      - POSTGRES_DB=fitness_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: