# version: '3.8'

# services:
#   db:
#     image: postgres
#     container_name: postgres_db
#     environment:
#       - POSTGRES_DB=fitness_db
#       - POSTGRES_USER=admin
#       - POSTGRES_PASSWORD=password
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     restart: unless-stopped

# volumes:
#   postgres_data:

version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      - POSTGRES_DB=fitness_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    container_name: django_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:password@db:5432/fitness_db
    restart: unless-stopped

  frontend:
    container_name: react_frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: